---
- name: Install default Apache2 Web Server
  hosts: all
  become: yes


  tasks:
  - name: Install Apache2
    apt: name=apache2 state=latest


  - name: Start Apache and make it enable on every reboot
    service: name=apache2 state=started enabled=yes
