---
- name: install docker.io
  apt:
    name: apache2
    state: latest
       
       
     
- docker_image:
    name: tomcat
    source: pull

- docker_container:
    name: tomcat
    state: started   
