---
- name: install docker.io
  apt:
    name: apache2
    state: latest
       
- name: add user to group docker
      user:
        name: "{{ user_1 }}"
        groups: docker
        append: yes     
     
- docker_image:
    name: tomcat
    source: pull

- docker_container:
    name: tomcat
    state: started   
