---

- name: Ensure group usergroup exists
  group:
    name: "{{ user_group }}"
    state: present


- name: Add the user 'max' with a specific uid and a primary group of 'somegroup'
  user:
    name: "{{ user_login }}"
    comment: "{{ user_login }}"
    shell: /bin/bash
    password: "{{ user_passwd }}"
    group: "{{ user_group }}"
