---
- name: Make user_and_group
  hosts: my_servers
  become: yes
  roles:
    - { role: user_dir, tags: [user_dir] }
    
- name: instaling docker.py start docker daemon, make docker container with nginx
  hosts: my_servers
  become: yes
  roles:
    - { role: dockers, tags: [dockers] }
  
