---

- name: Ensure group usergroup exists
  group:
    name: lesson5
    state: present


- name: Add the user 'lesson5' with a specific uid and a primary group of lesson5
  user:
    name: lesson5
    create_home: yes
    shell: /bin/bash
    password: 11111111
    group: lesson5

    

