---

- name: create group, user and "apps" dir
  block:
    - name:
      group:
        name: "{{ user_1 }}"
        state: present

    - name: Add the user 'lesson5' with a specific uid and a primary group of lesson5
      user:
        name: "{{ user_1 }}"
        create_home: yes
        shell: /bin/bash
        password: 11111111
        group: "{{ user_1 }}"
    
    - name: make dir
      file:
        path: /home/"{{ user_1 }}"/Apps
        state: directory
        mode: '0755'

  rescue:
    - name: Sending an e-mail using Gmail SMTP servers
      mail:
        host: smtp.gmail.com
        port: 587
        username: maxbm1991@gmail.com
        password: mysecret
        to: John Smith <john.smith@example.com>
        subject: Ansible-report
        body: System {{ ansible_hostname }} has been successfully provisioned.
      delegate_to: localhost

    

