---
- name: Make directory, file
  hosts: my_servers
  become: yes
  roles:
    - { role: makefile, tags: [makefile] }


- name: Make user_and_group
  hosts: my_servers
  become: yes
  roles:
    - makeuser
 
